/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Oficina.View.TelaLogin;

/**
 *
 * @author luqui
 */
public class TelaCadastroCarro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroCarro
     */
    public TelaCadastroCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marca:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 90, 70, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ano:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 50, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cor:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 60, 22);

        jLabel4.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modelo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 220, 80, 22);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Placa:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 260, 80, 22);

        jLabel6.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CADASTRAR CARRO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 10, 410, 43);
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(90, 90, 210, 20);
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(90, 140, 210, 20);
        getContentPane().add(jFormattedTextField3);
        jFormattedTextField3.setBounds(90, 180, 210, 20);
        getContentPane().add(jFormattedTextField4);
        jFormattedTextField4.setBounds(90, 220, 210, 20);
        getContentPane().add(jFormattedTextField5);
        jFormattedTextField5.setBounds(90, 260, 210, 20);

        jButton1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButton1.setText("Cadastrar");
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 290, 120, 31);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Oficina/View/Imagens/Tela de cadastro_1.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 520, 360);

        setBounds(0, 0, 538, 387);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
